# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for project
  pod 'CountryPickerSwift'
  pod 'SwiftPhoneNumberFormatter'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'FBSDKLoginKit'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  
end
